<?php

namespace Database\Seeders\Reports;

use App\Models\MainCore\Language;
use App\Models\MainCore\Translation;
use Illuminate\Database\Seeder;

class ReportsTranslationsSeeder extends Seeder
{
    public function run(): void
    {
        $english = Language::where('code', 'en')->first();
        $arabic = Language::where('code', 'ar')->first();

        if (!$english || !$arabic) {
            $this->command->warn('English or Arabic language not found. Skipping translations.');
            return;
        }

        $translations = [
            // Navigation Group
            'reports.navigation' => ['en' => 'Reports', 'ar' => 'التقارير'],

            // Common Filters
            'reports.filters.title' => ['en' => 'Report Filters', 'ar' => 'مرشحات التقرير'],
            'reports.filters.from_date' => ['en' => 'From Date', 'ar' => 'من تاريخ'],
            'reports.filters.to_date' => ['en' => 'To Date', 'ar' => 'إلى تاريخ'],
            'reports.filters.branch' => ['en' => 'Branch', 'ar' => 'الفرع'],
            'reports.filters.cost_center' => ['en' => 'Cost Center', 'ar' => 'مركز التكلفة'],
            'reports.filters.account' => ['en' => 'Account', 'ar' => 'الحساب'],
            'reports.filters.currency' => ['en' => 'Currency', 'ar' => 'العملة'],
            'reports.filters.project' => ['en' => 'Project', 'ar' => 'المشروع'],
            'reports.filters.fiscal_year' => ['en' => 'Fiscal Year', 'ar' => 'السنة المالية'],
            'reports.filters.period' => ['en' => 'Period', 'ar' => 'الفترة'],
            'reports.filters.include_zero_rows' => ['en' => 'Include Zero Rows', 'ar' => 'تضمين الصفوف الصفرية'],
            'reports.filters.posted_only' => ['en' => 'Posted Only', 'ar' => 'المسجلة فقط'],

            // Export Actions
            'reports.export.title' => ['en' => 'Export', 'ar' => 'تصدير'],
            'reports.export.print' => ['en' => 'Print', 'ar' => 'طباعة'],
            'reports.export.pdf' => ['en' => 'Export PDF', 'ar' => 'تصدير PDF'],
            'reports.export.excel' => ['en' => 'Export Excel', 'ar' => 'تصدير Excel'],

            // Common Metadata
            'reports.metadata.from_date' => ['en' => 'From Date', 'ar' => 'من تاريخ'],
            'reports.metadata.to_date' => ['en' => 'To Date', 'ar' => 'إلى تاريخ'],
            'reports.metadata.branch' => ['en' => 'Branch', 'ar' => 'الفرع'],
            'reports.metadata.cost_center' => ['en' => 'Cost Center', 'ar' => 'مركز التكلفة'],
            'reports.metadata.account' => ['en' => 'Account', 'ar' => 'الحساب'],
            'reports.metadata.currency' => ['en' => 'Currency', 'ar' => 'العملة'],
            'reports.metadata.generated_at' => ['en' => 'Generated At', 'ar' => 'تم الإنشاء في'],
            'reports.metadata.generated_by' => ['en' => 'Generated By', 'ar' => 'تم الإنشاء بواسطة'],

            // Common Messages
            'reports.no_data' => ['en' => 'No data available for export.', 'ar' => 'لا توجد بيانات متاحة للتصدير.'],
            'reports.generated_on' => ['en' => 'Generated on', 'ar' => 'تم الإنشاء في'],
            'reports.generated_by' => ['en' => 'Generated by', 'ar' => 'تم الإنشاء بواسطة'],
            'reports.yes' => ['en' => 'Yes', 'ar' => 'نعم'],
            'reports.no' => ['en' => 'No', 'ar' => 'لا'],

            // Summary
            'reports.summary.total_debit' => ['en' => 'Total Debit', 'ar' => 'إجمالي المدين'],
            'reports.summary.total_credit' => ['en' => 'Total Credit', 'ar' => 'إجمالي الدائن'],
            'reports.summary.net_balance' => ['en' => 'Net Balance', 'ar' => 'الرصيد الصافي'],
            'reports.summary.opening_balance' => ['en' => 'Opening Balance', 'ar' => 'الرصيد الافتتاحي'],
            'reports.summary.closing_balance' => ['en' => 'Closing Balance', 'ar' => 'الرصيد الختامي'],
            'reports.summary.total_revenue' => ['en' => 'Total Revenue', 'ar' => 'إجمالي الإيرادات'],
            'reports.summary.total_expenses' => ['en' => 'Total Expenses', 'ar' => 'إجمالي المصروفات'],
            'reports.summary.net_income' => ['en' => 'Net Income', 'ar' => 'صافي الدخل'],

            // Trial Balance
            'reports.trial_balance.navigation' => ['en' => 'Trial Balance', 'ar' => 'ميزان المراجعة'],
            'reports.trial_balance.title' => ['en' => 'Trial Balance', 'ar' => 'ميزان المراجعة'],
            'pages.reports.trial_balance.title' => ['en' => 'Trial Balance', 'ar' => 'ميزان المراجعة'],
            'reports.trial_balance.account_code' => ['en' => 'Account Code', 'ar' => 'رمز الحساب'],
            'reports.trial_balance.account_name' => ['en' => 'Account Name', 'ar' => 'اسم الحساب'],
            'reports.trial_balance.account_type' => ['en' => 'Type', 'ar' => 'النوع'],
            'reports.trial_balance.debits' => ['en' => 'Debits', 'ar' => 'مدين'],
            'reports.trial_balance.credits' => ['en' => 'Credits', 'ar' => 'دائن'],
            'reports.trial_balance.balance' => ['en' => 'Balance', 'ar' => 'الرصيد'],
            'reports.trial_balance.not_balanced' => ['en' => 'Trial balance is not balanced. Debits do not equal credits.', 'ar' => 'ميزان المراجعة غير متوازن. المدين لا يساوي الدائن.'],

            // General Ledger
            'reports.general_ledger.navigation' => ['en' => 'General Ledger', 'ar' => 'دفتر الأستاذ العام'],
            'reports.general_ledger.title' => ['en' => 'General Ledger', 'ar' => 'دفتر الأستاذ العام'],
            'pages.reports.general_ledger.title' => ['en' => 'General Ledger', 'ar' => 'دفتر الأستاذ العام'],
            'reports.general_ledger.date' => ['en' => 'Date', 'ar' => 'التاريخ'],
            'reports.general_ledger.entry_number' => ['en' => 'Entry #', 'ar' => 'رقم القيد'],
            'reports.general_ledger.reference' => ['en' => 'Reference', 'ar' => 'المرجع'],
            'reports.general_ledger.description' => ['en' => 'Description', 'ar' => 'الوصف'],
            'reports.general_ledger.debit' => ['en' => 'Debit', 'ar' => 'مدين'],
            'reports.general_ledger.credit' => ['en' => 'Credit', 'ar' => 'دائن'],
            'reports.general_ledger.balance' => ['en' => 'Balance', 'ar' => 'الرصيد'],
            'reports.general_ledger.branch' => ['en' => 'Branch', 'ar' => 'الفرع'],
            'reports.general_ledger.cost_center' => ['en' => 'Cost Center', 'ar' => 'مركز التكلفة'],
            'reports.general_ledger.opening_balance' => ['en' => 'Opening Balance', 'ar' => 'الرصيد الافتتاحي'],
            'reports.general_ledger.not_balanced' => ['en' => 'General ledger is not balanced. Debits do not equal credits.', 'ar' => 'دفتر الأستاذ العام غير متوازن. المدين لا يساوي الدائن.'],

            // Income Statement
            'reports.income_statement.navigation' => ['en' => 'Income Statement', 'ar' => 'قائمة الدخل'],
            'reports.income_statement.title' => ['en' => 'Income Statement', 'ar' => 'قائمة الدخل'],
            'pages.reports.income_statement.title' => ['en' => 'Income Statement', 'ar' => 'قائمة الدخل'],
            'reports.income_statement.account_code' => ['en' => 'Account Code', 'ar' => 'رمز الحساب'],
            'reports.income_statement.account_name' => ['en' => 'Account Name', 'ar' => 'اسم الحساب'],
            'reports.income_statement.amount' => ['en' => 'Amount', 'ar' => 'المبلغ'],
            'reports.income_statement.revenue' => ['en' => 'REVENUE', 'ar' => 'الإيرادات'],
            'reports.income_statement.expenses' => ['en' => 'EXPENSES', 'ar' => 'المصروفات'],
            'reports.income_statement.total_revenue' => ['en' => 'Total Revenue', 'ar' => 'إجمالي الإيرادات'],
            'reports.income_statement.total_expenses' => ['en' => 'Total Expenses', 'ar' => 'إجمالي المصروفات'],
            'reports.income_statement.net_income' => ['en' => 'NET INCOME', 'ar' => 'صافي الدخل'],

            // Account Statement
            'reports.account_statement.navigation' => ['en' => 'Account Statement', 'ar' => 'كشف حساب'],
            'reports.account_statement.title' => ['en' => 'Account Statement', 'ar' => 'كشف حساب'],
            'pages.reports.account_statement.title' => ['en' => 'Account Statement', 'ar' => 'كشف حساب'],
            'reports.account_statement.opening_balance' => ['en' => 'Opening Balance', 'ar' => 'الرصيد الافتتاحي'],

            // Balance Sheet
            'reports.balance_sheet.navigation' => ['en' => 'Balance Sheet', 'ar' => 'الميزانية العمومية'],
            'reports.balance_sheet.title' => ['en' => 'Balance Sheet', 'ar' => 'الميزانية العمومية'],
            'pages.reports.balance_sheet.title' => ['en' => 'Balance Sheet', 'ar' => 'الميزانية العمومية'],
            'reports.balance_sheet.assets' => ['en' => 'ASSETS', 'ar' => 'الأصول'],
            'reports.balance_sheet.liabilities' => ['en' => 'LIABILITIES', 'ar' => 'الخصوم'],
            'reports.balance_sheet.equity' => ['en' => 'EQUITY', 'ar' => 'حقوق الملكية'],
            'reports.balance_sheet.total_assets' => ['en' => 'Total Assets', 'ar' => 'إجمالي الأصول'],
            'reports.balance_sheet.total_liabilities' => ['en' => 'Total Liabilities', 'ar' => 'إجمالي الخصوم'],
            'reports.balance_sheet.total_equity' => ['en' => 'Total Equity', 'ar' => 'إجمالي حقوق الملكية'],
            'reports.balance_sheet.total_liabilities_equity' => ['en' => 'Total Liabilities & Equity', 'ar' => 'إجمالي الخصوم وحقوق الملكية'],
            'reports.balance_sheet.account_code' => ['en' => 'Account Code', 'ar' => 'رمز الحساب'],
            'reports.balance_sheet.account_name' => ['en' => 'Account Name', 'ar' => 'اسم الحساب'],
            'reports.balance_sheet.balance' => ['en' => 'Balance', 'ar' => 'الرصيد'],
            'reports.balance_sheet.not_balanced' => ['en' => 'Balance sheet is not balanced. Assets do not equal Liabilities + Equity.', 'ar' => 'الميزانية العمومية غير متوازنة. الأصول لا تساوي الخصوم + حقوق الملكية.'],

            // Cash Flow
            'reports.cash_flow.navigation' => ['en' => 'Cash Flow', 'ar' => 'تقرير التدفقات النقدية'],
            'reports.cash_flow.title' => ['en' => 'Cash Flow Statement', 'ar' => 'تقرير التدفقات النقدية'],
            'pages.reports.cash_flow.title' => ['en' => 'Cash Flow Statement', 'ar' => 'تقرير التدفقات النقدية'],
            'reports.cash_flow.date' => ['en' => 'Date', 'ar' => 'التاريخ'],
            'reports.cash_flow.type' => ['en' => 'Type', 'ar' => 'النوع'],
            'reports.cash_flow.voucher_number' => ['en' => 'Voucher #', 'ar' => 'رقم السند'],
            'reports.cash_flow.description' => ['en' => 'Description', 'ar' => 'الوصف'],
            'reports.cash_flow.cash_in' => ['en' => 'Cash In', 'ar' => 'نقد وارد'],
            'reports.cash_flow.cash_out' => ['en' => 'Cash Out', 'ar' => 'نقد صادر'],
            'reports.cash_flow.receipt' => ['en' => 'Receipt', 'ar' => 'سند قبض'],
            'reports.cash_flow.payment' => ['en' => 'Payment', 'ar' => 'سند دفع'],
            'reports.cash_flow.opening_balance' => ['en' => 'Opening Balance', 'ar' => 'الرصيد الافتتاحي'],
            'reports.cash_flow.total_cash_in' => ['en' => 'Total Cash In', 'ar' => 'إجمالي النقد الوارد'],
            'reports.cash_flow.total_cash_out' => ['en' => 'Total Cash Out', 'ar' => 'إجمالي النقد الصادر'],
            'reports.cash_flow.net_cash_flow' => ['en' => 'Net Cash Flow', 'ar' => 'صافي التدفق النقدي'],
            'reports.cash_flow.closing_balance' => ['en' => 'Closing Balance', 'ar' => 'الرصيد الختامي'],

            // VAT Report
            'reports.vat.navigation' => ['en' => 'VAT Report', 'ar' => 'تقرير القيمة المضافة'],
            'reports.vat.title' => ['en' => 'VAT Report', 'ar' => 'تقرير القيمة المضافة'],
            'pages.reports.vat.title' => ['en' => 'VAT Report', 'ar' => 'تقرير القيمة المضافة'],

            // Fixed Assets
            'reports.fixed_assets.navigation' => ['en' => 'Fixed Assets Report', 'ar' => 'تقرير الأصول الثابتة'],
            'reports.fixed_assets.title' => ['en' => 'Fixed Assets Report', 'ar' => 'تقرير الأصول الثابتة'],
            'pages.reports.fixed_assets.title' => ['en' => 'Fixed Assets Report', 'ar' => 'تقرير الأصول الثابتة'],

            // Journal Entries by Year
            'reports.journal_entries_by_year.navigation' => ['en' => 'Journal Entries by Year', 'ar' => 'تقرير القيود حسب السنة'],
            'reports.journal_entries_by_year.title' => ['en' => 'Journal Entries by Year', 'ar' => 'تقرير القيود حسب السنة'],
            'pages.reports.journal_entries_by_year.title' => ['en' => 'Journal Entries by Year', 'ar' => 'تقرير القيود حسب السنة'],

            // A/R Customers
            'reports.accounts_receivable.navigation' => ['en' => 'A/R Customers', 'ar' => 'تقرير ديون العملاء'],
            'reports.accounts_receivable.title' => ['en' => 'Accounts Receivable Report', 'ar' => 'تقرير ديون العملاء'],
            'pages.reports.accounts_receivable.title' => ['en' => 'Accounts Receivable Report', 'ar' => 'تقرير ديون العملاء'],

            // A/P Aging Current
            'reports.accounts_payable_aging_current.navigation' => ['en' => 'A/P Aging Current', 'ar' => 'أعمار الديون المدينة'],
            'reports.accounts_payable_aging_current.title' => ['en' => 'Accounts Payable Aging (Current)', 'ar' => 'أعمار الديون المدينة'],
            'pages.reports.accounts_payable_aging_current.title' => ['en' => 'Accounts Payable Aging (Current)', 'ar' => 'أعمار الديون المدينة'],

            // A/P Aging Overdue
            'reports.accounts_payable_aging_overdue.navigation' => ['en' => 'A/P Aging Overdue', 'ar' => 'أعمار الديون الدائنة'],
            'reports.accounts_payable_aging_overdue.title' => ['en' => 'Accounts Payable Aging (Overdue)', 'ar' => 'أعمار الديون الدائنة'],
            'pages.reports.accounts_payable_aging_overdue.title' => ['en' => 'Accounts Payable Aging (Overdue)', 'ar' => 'أعمار الديون الدائنة'],

            // Financial Position
            'reports.financial_position.navigation' => ['en' => 'Financial Position', 'ar' => 'تقرير المركز المالي'],
            'reports.financial_position.title' => ['en' => 'Financial Position Report', 'ar' => 'تقرير المركز المالي'],
            'pages.reports.financial_position.title' => ['en' => 'Financial Position Report', 'ar' => 'تقرير المركز المالي'],

            // Changes in Equity
            'reports.changes_in_equity.navigation' => ['en' => 'Changes in Equity', 'ar' => 'التغيرات في حقوق الملكية'],
            'reports.changes_in_equity.title' => ['en' => 'Changes in Equity', 'ar' => 'التغيرات في حقوق الملكية'],
            'pages.reports.changes_in_equity.title' => ['en' => 'Changes in Equity', 'ar' => 'التغيرات في حقوق الملكية'],

            // Financial Performance
            'reports.financial_performance.navigation' => ['en' => 'Financial Performance', 'ar' => 'الأداء المالي'],
            'reports.financial_performance.title' => ['en' => 'Financial Performance Report', 'ar' => 'تقرير الأداء المالي'],
            'pages.reports.financial_performance.title' => ['en' => 'Financial Performance Report', 'ar' => 'تقرير الأداء المالي'],

            // Comparisons
            'reports.comparisons.navigation' => ['en' => 'Comparisons Report', 'ar' => 'تقرير المقارنات'],
            'reports.comparisons.title' => ['en' => 'Comparisons Report', 'ar' => 'تقرير المقارنات'],
            'pages.reports.comparisons.title' => ['en' => 'Comparisons Report', 'ar' => 'تقرير المقارنات'],
            'reports.comparisons.period' => ['en' => 'Period', 'ar' => 'الفترة'],
            'reports.comparisons.period_a' => ['en' => 'Period A', 'ar' => 'الفترة أ'],
            'reports.comparisons.period_b' => ['en' => 'Period B', 'ar' => 'الفترة ب'],
            'reports.comparisons.from_date' => ['en' => 'From Date', 'ar' => 'من تاريخ'],
            'reports.comparisons.to_date' => ['en' => 'To Date', 'ar' => 'إلى تاريخ'],
            'reports.comparisons.amount' => ['en' => 'Amount', 'ar' => 'المبلغ'],
            'reports.comparisons.variance' => ['en' => 'Variance', 'ar' => 'الفرق'],
            'reports.comparisons.variance_percent' => ['en' => 'Variance %', 'ar' => 'نسبة الفرق'],

            // Additional translations
            'reports.vat.date' => ['en' => 'Date', 'ar' => 'التاريخ'],
            'reports.vat.account_code' => ['en' => 'Account Code', 'ar' => 'رمز الحساب'],
            'reports.vat.account_name' => ['en' => 'Account Name', 'ar' => 'اسم الحساب'],
            'reports.vat.entry_number' => ['en' => 'Entry #', 'ar' => 'رقم القيد'],
            'reports.vat.output_vat' => ['en' => 'Output VAT', 'ar' => 'ضريبة المخرجات'],
            'reports.vat.input_vat' => ['en' => 'Input VAT', 'ar' => 'ضريبة المدخلات'],
            'reports.vat.total_output_vat' => ['en' => 'Total Output VAT', 'ar' => 'إجمالي ضريبة المخرجات'],
            'reports.vat.total_input_vat' => ['en' => 'Total Input VAT', 'ar' => 'إجمالي ضريبة المدخلات'],
            'reports.vat.net_vat' => ['en' => 'Net VAT', 'ar' => 'صافي الضريبة'],

            'reports.fixed_assets.code' => ['en' => 'Code', 'ar' => 'الرمز'],
            'reports.fixed_assets.name' => ['en' => 'Name', 'ar' => 'الاسم'],
            'reports.fixed_assets.category' => ['en' => 'Category', 'ar' => 'الفئة'],
            'reports.fixed_assets.purchase_date' => ['en' => 'Purchase Date', 'ar' => 'تاريخ الشراء'],
            'reports.fixed_assets.acquisition_cost' => ['en' => 'Acquisition Cost', 'ar' => 'تكلفة الاستحواذ'],
            'reports.fixed_assets.depreciation' => ['en' => 'Depreciation', 'ar' => 'الاستهلاك'],
            'reports.fixed_assets.net_book_value' => ['en' => 'Net Book Value', 'ar' => 'القيمة الدفترية الصافية'],
            'reports.fixed_assets.status' => ['en' => 'Status', 'ar' => 'الحالة'],

            'reports.journal_entries_by_year.year' => ['en' => 'Year', 'ar' => 'السنة'],
            'reports.journal_entries_by_year.month' => ['en' => 'Month', 'ar' => 'الشهر'],
            'reports.journal_entries_by_year.entry_count' => ['en' => 'Entry Count', 'ar' => 'عدد القيود'],
            'reports.journal_entries_by_year.total_debit' => ['en' => 'Total Debit', 'ar' => 'إجمالي المدين'],
            'reports.journal_entries_by_year.total_credit' => ['en' => 'Total Credit', 'ar' => 'إجمالي الدائن'],

            'reports.accounts_receivable.customer_code' => ['en' => 'Customer Code', 'ar' => 'رمز العميل'],
            'reports.accounts_receivable.customer_name' => ['en' => 'Customer Name', 'ar' => 'اسم العميل'],
            'reports.accounts_receivable.balance' => ['en' => 'Balance', 'ar' => 'الرصيد'],
            'reports.accounts_receivable.credit_limit' => ['en' => 'Credit Limit', 'ar' => 'حد الائتمان'],

            'reports.accounts_payable_aging_current.supplier' => ['en' => 'Supplier', 'ar' => 'المورد'],
            'reports.accounts_payable_aging_current.current' => ['en' => '0-30 Days', 'ar' => '0-30 يوم'],
            'reports.accounts_payable_aging_current.days_31_60' => ['en' => '31-60 Days', 'ar' => '31-60 يوم'],
            'reports.accounts_payable_aging_current.days_61_90' => ['en' => '61-90 Days', 'ar' => '61-90 يوم'],
            'reports.accounts_payable_aging_current.over_90' => ['en' => 'Over 90 Days', 'ar' => 'أكثر من 90 يوم'],
            'reports.accounts_payable_aging_current.total' => ['en' => 'Total', 'ar' => 'الإجمالي'],

            'reports.accounts_payable_aging_overdue.supplier' => ['en' => 'Supplier', 'ar' => 'المورد'],
            'reports.accounts_payable_aging_overdue.overdue_amount' => ['en' => 'Overdue Amount', 'ar' => 'المبلغ المتأخر'],
            'reports.accounts_payable_aging_overdue.days_overdue' => ['en' => 'Days Overdue', 'ar' => 'أيام التأخير'],

            'reports.financial_position.branch' => ['en' => 'Branch', 'ar' => 'الفرع'],
            'reports.financial_position.cost_center' => ['en' => 'Cost Center', 'ar' => 'مركز التكلفة'],
            'reports.financial_position.total_debit' => ['en' => 'Total Debit', 'ar' => 'إجمالي المدين'],
            'reports.financial_position.total_credit' => ['en' => 'Total Credit', 'ar' => 'إجمالي الدائن'],
            'reports.financial_position.balance' => ['en' => 'Balance', 'ar' => 'الرصيد'],

            'reports.changes_in_equity.date' => ['en' => 'Date', 'ar' => 'التاريخ'],
            'reports.changes_in_equity.account_code' => ['en' => 'Account Code', 'ar' => 'رمز الحساب'],
            'reports.changes_in_equity.account_name' => ['en' => 'Account Name', 'ar' => 'اسم الحساب'],
            'reports.changes_in_equity.description' => ['en' => 'Description', 'ar' => 'الوصف'],
            'reports.changes_in_equity.movement' => ['en' => 'Movement', 'ar' => 'الحركة'],
            'reports.changes_in_equity.opening_equity' => ['en' => 'Opening Equity', 'ar' => 'حقوق الملكية الافتتاحية'],
            'reports.changes_in_equity.total_movements' => ['en' => 'Total Movements', 'ar' => 'إجمالي الحركات'],
            'reports.changes_in_equity.closing_equity' => ['en' => 'Closing Equity', 'ar' => 'حقوق الملكية الختامية'],

            'reports.financial_performance.kpi' => ['en' => 'KPI', 'ar' => 'مؤشر الأداء'],
            'reports.financial_performance.value' => ['en' => 'Value', 'ar' => 'القيمة'],
            'reports.financial_performance.percentage' => ['en' => 'Percentage', 'ar' => 'النسبة'],
            'reports.financial_performance.revenue' => ['en' => 'Revenue', 'ar' => 'الإيرادات'],
            'reports.financial_performance.expenses' => ['en' => 'Expenses', 'ar' => 'المصروفات'],
            'reports.financial_performance.net_income' => ['en' => 'Net Income', 'ar' => 'صافي الدخل'],
            'reports.financial_performance.gross_margin' => ['en' => 'Gross Margin %', 'ar' => 'هامش الربح الإجمالي %'],
            'reports.financial_performance.net_margin' => ['en' => 'Net Margin %', 'ar' => 'هامش الربح الصافي %'],
        ];

        foreach ($translations as $key => $values) {
            // English translation
            Translation::updateOrCreate(
                [
                    'key' => $key,
                    'group' => 'dashboard',
                    'language_id' => $english->id,
                ],
                [
                    'value' => $values['en'],
                ]
            );

            // Arabic translation
            Translation::updateOrCreate(
                [
                    'key' => $key,
                    'group' => 'dashboard',
                    'language_id' => $arabic->id,
                ],
                [
                    'value' => $values['ar'],
                ]
            );
        }

        $this->command->info('Reports translations seeded successfully!');
    }
}

