<?php

namespace Database\Seeders\MainCore;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $countries = $this->countries(); // 196 entries

        // ✅ تحذير لو العدد اختلف (عشان تبقى مطمن)
        if (count($countries) !== 196) {
            $this->command?->warn('Countries count is '.count($countries).' (expected 196).');
        }

        // ✅ Upsert سريع (MySQL)
        foreach (array_chunk($countries, 500) as $chunk) {
            foreach ($chunk as $c) {
                DB::table('countries')->updateOrInsert(
                    ['iso2' => $c['iso2']],
                    [
                        'iso3' => $c['iso3'] ?? null,
                        'name' => json_encode([
                            'en' => $c['name_en'],
                            'ar' => $c['name_ar'] ?? null,
                        ], JSON_UNESCAPED_UNICODE),
                        'is_active' => true,
                        'updated_at' => $now,
                        'created_at' => $now,
                    ]
                );
            }
        }

        $this->command?->info('✓ Countries seeded: '.count($countries));
    }

    private function countries(): array
    {
        // 193 UN members + Palestine (PS) + Vatican (VA) + Taiwan (TW) = 196
        return [
            ['iso2'=>'AF','iso3'=>'AFG','name_en'=>'Afghanistan','name_ar'=>'أفغانستان'],
            ['iso2'=>'AL','iso3'=>'ALB','name_en'=>'Albania','name_ar'=>'ألبانيا'],
            ['iso2'=>'DZ','iso3'=>'DZA','name_en'=>'Algeria','name_ar'=>'الجزائر'],
            ['iso2'=>'AD','iso3'=>'AND','name_en'=>'Andorra','name_ar'=>'أندورا'],
            ['iso2'=>'AO','iso3'=>'AGO','name_en'=>'Angola','name_ar'=>'أنغولا'],
            ['iso2'=>'AG','iso3'=>'ATG','name_en'=>'Antigua and Barbuda','name_ar'=>'أنتيغوا وبربودا'],
            ['iso2'=>'AR','iso3'=>'ARG','name_en'=>'Argentina','name_ar'=>'الأرجنتين'],
            ['iso2'=>'AM','iso3'=>'ARM','name_en'=>'Armenia','name_ar'=>'أرمينيا'],
            ['iso2'=>'AU','iso3'=>'AUS','name_en'=>'Australia','name_ar'=>'أستراليا'],
            ['iso2'=>'AT','iso3'=>'AUT','name_en'=>'Austria','name_ar'=>'النمسا'],
            ['iso2'=>'AZ','iso3'=>'AZE','name_en'=>'Azerbaijan','name_ar'=>'أذربيجان'],
            ['iso2'=>'BS','iso3'=>'BHS','name_en'=>'Bahamas','name_ar'=>'جزر البهاما'],
            ['iso2'=>'BH','iso3'=>'BHR','name_en'=>'Bahrain','name_ar'=>'البحرين'],
            ['iso2'=>'BD','iso3'=>'BGD','name_en'=>'Bangladesh','name_ar'=>'بنغلاديش'],
            ['iso2'=>'BB','iso3'=>'BRB','name_en'=>'Barbados','name_ar'=>'باربادوس'],
            ['iso2'=>'BY','iso3'=>'BLR','name_en'=>'Belarus','name_ar'=>'بيلاروسيا'],
            ['iso2'=>'BE','iso3'=>'BEL','name_en'=>'Belgium','name_ar'=>'بلجيكا'],
            ['iso2'=>'BZ','iso3'=>'BLZ','name_en'=>'Belize','name_ar'=>'بليز'],
            ['iso2'=>'BJ','iso3'=>'BEN','name_en'=>'Benin','name_ar'=>'بنين'],
            ['iso2'=>'BT','iso3'=>'BTN','name_en'=>'Bhutan','name_ar'=>'بوتان'],
            ['iso2'=>'BO','iso3'=>'BOL','name_en'=>'Bolivia','name_ar'=>'بوليفيا'],
            ['iso2'=>'BA','iso3'=>'BIH','name_en'=>'Bosnia and Herzegovina','name_ar'=>'البوسنة والهرسك'],
            ['iso2'=>'BW','iso3'=>'BWA','name_en'=>'Botswana','name_ar'=>'بوتسوانا'],
            ['iso2'=>'BR','iso3'=>'BRA','name_en'=>'Brazil','name_ar'=>'البرازيل'],
            ['iso2'=>'BN','iso3'=>'BRN','name_en'=>'Brunei','name_ar'=>'بروناي'],
            ['iso2'=>'BG','iso3'=>'BGR','name_en'=>'Bulgaria','name_ar'=>'بلغاريا'],
            ['iso2'=>'BF','iso3'=>'BFA','name_en'=>'Burkina Faso','name_ar'=>'بوركينا فاسو'],
            ['iso2'=>'BI','iso3'=>'BDI','name_en'=>'Burundi','name_ar'=>'بوروندي'],
            ['iso2'=>'CV','iso3'=>'CPV','name_en'=>'Cabo Verde','name_ar'=>'الرأس الأخضر'],
            ['iso2'=>'KH','iso3'=>'KHM','name_en'=>'Cambodia','name_ar'=>'كمبوديا'],
            ['iso2'=>'CM','iso3'=>'CMR','name_en'=>'Cameroon','name_ar'=>'الكاميرون'],
            ['iso2'=>'CA','iso3'=>'CAN','name_en'=>'Canada','name_ar'=>'كندا'],
            ['iso2'=>'CF','iso3'=>'CAF','name_en'=>'Central African Republic','name_ar'=>'جمهورية أفريقيا الوسطى'],
            ['iso2'=>'TD','iso3'=>'TCD','name_en'=>'Chad','name_ar'=>'تشاد'],
            ['iso2'=>'CL','iso3'=>'CHL','name_en'=>'Chile','name_ar'=>'تشيلي'],
            ['iso2'=>'CN','iso3'=>'CHN','name_en'=>'China','name_ar'=>'الصين'],
            ['iso2'=>'CO','iso3'=>'COL','name_en'=>'Colombia','name_ar'=>'كولومبيا'],
            ['iso2'=>'KM','iso3'=>'COM','name_en'=>'Comoros','name_ar'=>'جزر القمر'],
            ['iso2'=>'CG','iso3'=>'COG','name_en'=>'Congo (Republic of the)','name_ar'=>'جمهورية الكونغو'],
            ['iso2'=>'CD','iso3'=>'COD','name_en'=>'Congo (Democratic Republic of the)','name_ar'=>'الكونغو الديمقراطية'],
            ['iso2'=>'CR','iso3'=>'CRI','name_en'=>'Costa Rica','name_ar'=>'كوستاريكا'],
            ['iso2'=>'CI','iso3'=>'CIV','name_en'=>"Côte d’Ivoire",'name_ar'=>'ساحل العاج'],
            ['iso2'=>'HR','iso3'=>'HRV','name_en'=>'Croatia','name_ar'=>'كرواتيا'],
            ['iso2'=>'CU','iso3'=>'CUB','name_en'=>'Cuba','name_ar'=>'كوبا'],
            ['iso2'=>'CY','iso3'=>'CYP','name_en'=>'Cyprus','name_ar'=>'قبرص'],
            ['iso2'=>'CZ','iso3'=>'CZE','name_en'=>'Czechia','name_ar'=>'التشيك'],
            ['iso2'=>'DK','iso3'=>'DNK','name_en'=>'Denmark','name_ar'=>'الدنمارك'],
            ['iso2'=>'DJ','iso3'=>'DJI','name_en'=>'Djibouti','name_ar'=>'جيبوتي'],
            ['iso2'=>'DM','iso3'=>'DMA','name_en'=>'Dominica','name_ar'=>'دومينيكا'],
            ['iso2'=>'DO','iso3'=>'DOM','name_en'=>'Dominican Republic','name_ar'=>'جمهورية الدومينيكان'],
            ['iso2'=>'EC','iso3'=>'ECU','name_en'=>'Ecuador','name_ar'=>'الإكوادور'],
            ['iso2'=>'EG','iso3'=>'EGY','name_en'=>'Egypt','name_ar'=>'مصر'],
            ['iso2'=>'SV','iso3'=>'SLV','name_en'=>'El Salvador','name_ar'=>'السلفادور'],
            ['iso2'=>'GQ','iso3'=>'GNQ','name_en'=>'Equatorial Guinea','name_ar'=>'غينيا الاستوائية'],
            ['iso2'=>'ER','iso3'=>'ERI','name_en'=>'Eritrea','name_ar'=>'إريتريا'],
            ['iso2'=>'EE','iso3'=>'EST','name_en'=>'Estonia','name_ar'=>'إستونيا'],
            ['iso2'=>'SZ','iso3'=>'SWZ','name_en'=>'Eswatini','name_ar'=>'إسواتيني'],
            ['iso2'=>'ET','iso3'=>'ETH','name_en'=>'Ethiopia','name_ar'=>'إثيوبيا'],
            ['iso2'=>'FJ','iso3'=>'FJI','name_en'=>'Fiji','name_ar'=>'فيجي'],
            ['iso2'=>'FI','iso3'=>'FIN','name_en'=>'Finland','name_ar'=>'فنلندا'],
            ['iso2'=>'FR','iso3'=>'FRA','name_en'=>'France','name_ar'=>'فرنسا'],
            ['iso2'=>'GA','iso3'=>'GAB','name_en'=>'Gabon','name_ar'=>'الغابون'],
            ['iso2'=>'GM','iso3'=>'GMB','name_en'=>'Gambia','name_ar'=>'غامبيا'],
            ['iso2'=>'GE','iso3'=>'GEO','name_en'=>'Georgia','name_ar'=>'جورجيا'],
            ['iso2'=>'DE','iso3'=>'DEU','name_en'=>'Germany','name_ar'=>'ألمانيا'],
            ['iso2'=>'GH','iso3'=>'GHA','name_en'=>'Ghana','name_ar'=>'غانا'],
            ['iso2'=>'GR','iso3'=>'GRC','name_en'=>'Greece','name_ar'=>'اليونان'],
            ['iso2'=>'GD','iso3'=>'GRD','name_en'=>'Grenada','name_ar'=>'غرينادا'],
            ['iso2'=>'GT','iso3'=>'GTM','name_en'=>'Guatemala','name_ar'=>'غواتيمالا'],
            ['iso2'=>'GN','iso3'=>'GIN','name_en'=>'Guinea','name_ar'=>'غينيا'],
            ['iso2'=>'GW','iso3'=>'GNB','name_en'=>'Guinea-Bissau','name_ar'=>'غينيا بيساو'],
            ['iso2'=>'GY','iso3'=>'GUY','name_en'=>'Guyana','name_ar'=>'غيانا'],
            ['iso2'=>'HT','iso3'=>'HTI','name_en'=>'Haiti','name_ar'=>'هايتي'],
            ['iso2'=>'HN','iso3'=>'HND','name_en'=>'Honduras','name_ar'=>'هندوراس'],
            ['iso2'=>'HU','iso3'=>'HUN','name_en'=>'Hungary','name_ar'=>'المجر'],
            ['iso2'=>'IS','iso3'=>'ISL','name_en'=>'Iceland','name_ar'=>'آيسلندا'],
            ['iso2'=>'IN','iso3'=>'IND','name_en'=>'India','name_ar'=>'الهند'],
            ['iso2'=>'ID','iso3'=>'IDN','name_en'=>'Indonesia','name_ar'=>'إندونيسيا'],
            ['iso2'=>'IR','iso3'=>'IRN','name_en'=>'Iran','name_ar'=>'إيران'],
            ['iso2'=>'IQ','iso3'=>'IRQ','name_en'=>'Iraq','name_ar'=>'العراق'],
            ['iso2'=>'IE','iso3'=>'IRL','name_en'=>'Ireland','name_ar'=>'أيرلندا'],
            ['iso2'=>'IL','iso3'=>'ISR','name_en'=>'Israel','name_ar'=>'إسرائيل'],
            ['iso2'=>'IT','iso3'=>'ITA','name_en'=>'Italy','name_ar'=>'إيطاليا'],
            ['iso2'=>'JM','iso3'=>'JAM','name_en'=>'Jamaica','name_ar'=>'جامايكا'],
            ['iso2'=>'JP','iso3'=>'JPN','name_en'=>'Japan','name_ar'=>'اليابان'],
            ['iso2'=>'JO','iso3'=>'JOR','name_en'=>'Jordan','name_ar'=>'الأردن'],
            ['iso2'=>'KZ','iso3'=>'KAZ','name_en'=>'Kazakhstan','name_ar'=>'كازاخستان'],
            ['iso2'=>'KE','iso3'=>'KEN','name_en'=>'Kenya','name_ar'=>'كينيا'],
            ['iso2'=>'KI','iso3'=>'KIR','name_en'=>'Kiribati','name_ar'=>'كيريباتي'],
            ['iso2'=>'KP','iso3'=>'PRK','name_en'=>'Korea (North)','name_ar'=>'كوريا الشمالية'],
            ['iso2'=>'KR','iso3'=>'KOR','name_en'=>'Korea (South)','name_ar'=>'كوريا الجنوبية'],
            ['iso2'=>'KW','iso3'=>'KWT','name_en'=>'Kuwait','name_ar'=>'الكويت'],
            ['iso2'=>'KG','iso3'=>'KGZ','name_en'=>'Kyrgyzstan','name_ar'=>'قيرغيزستان'],
            ['iso2'=>'LA','iso3'=>'LAO','name_en'=>'Laos','name_ar'=>'لاوس'],
            ['iso2'=>'LV','iso3'=>'LVA','name_en'=>'Latvia','name_ar'=>'لاتفيا'],
            ['iso2'=>'LB','iso3'=>'LBN','name_en'=>'Lebanon','name_ar'=>'لبنان'],
            ['iso2'=>'LS','iso3'=>'LSO','name_en'=>'Lesotho','name_ar'=>'ليسوتو'],
            ['iso2'=>'LR','iso3'=>'LBR','name_en'=>'Liberia','name_ar'=>'ليبيريا'],
            ['iso2'=>'LY','iso3'=>'LBY','name_en'=>'Libya','name_ar'=>'ليبيا'],
            ['iso2'=>'LI','iso3'=>'LIE','name_en'=>'Liechtenstein','name_ar'=>'ليختنشتاين'],
            ['iso2'=>'LT','iso3'=>'LTU','name_en'=>'Lithuania','name_ar'=>'ليتوانيا'],
            ['iso2'=>'LU','iso3'=>'LUX','name_en'=>'Luxembourg','name_ar'=>'لوكسمبورغ'],
            ['iso2'=>'MG','iso3'=>'MDG','name_en'=>'Madagascar','name_ar'=>'مدغشقر'],
            ['iso2'=>'MW','iso3'=>'MWI','name_en'=>'Malawi','name_ar'=>'ملاوي'],
            ['iso2'=>'MY','iso3'=>'MYS','name_en'=>'Malaysia','name_ar'=>'ماليزيا'],
            ['iso2'=>'MV','iso3'=>'MDV','name_en'=>'Maldives','name_ar'=>'جزر المالديف'],
            ['iso2'=>'ML','iso3'=>'MLI','name_en'=>'Mali','name_ar'=>'مالي'],
            ['iso2'=>'MT','iso3'=>'MLT','name_en'=>'Malta','name_ar'=>'مالطا'],
            ['iso2'=>'MH','iso3'=>'MHL','name_en'=>'Marshall Islands','name_ar'=>'جزر مارشال'],
            ['iso2'=>'MR','iso3'=>'MRT','name_en'=>'Mauritania','name_ar'=>'موريتانيا'],
            ['iso2'=>'MU','iso3'=>'MUS','name_en'=>'Mauritius','name_ar'=>'موريشيوس'],
            ['iso2'=>'MX','iso3'=>'MEX','name_en'=>'Mexico','name_ar'=>'المكسيك'],
            ['iso2'=>'FM','iso3'=>'FSM','name_en'=>'Micronesia','name_ar'=>'ميكرونيزيا'],
            ['iso2'=>'MD','iso3'=>'MDA','name_en'=>'Moldova','name_ar'=>'مولدوفا'],
            ['iso2'=>'MC','iso3'=>'MCO','name_en'=>'Monaco','name_ar'=>'موناكو'],
            ['iso2'=>'MN','iso3'=>'MNG','name_en'=>'Mongolia','name_ar'=>'منغوليا'],
            ['iso2'=>'ME','iso3'=>'MNE','name_en'=>'Montenegro','name_ar'=>'الجبل الأسود'],
            ['iso2'=>'MA','iso3'=>'MAR','name_en'=>'Morocco','name_ar'=>'المغرب'],
            ['iso2'=>'MZ','iso3'=>'MOZ','name_en'=>'Mozambique','name_ar'=>'موزمبيق'],
            ['iso2'=>'MM','iso3'=>'MMR','name_en'=>'Myanmar','name_ar'=>'ميانمار'],
            ['iso2'=>'NA','iso3'=>'NAM','name_en'=>'Namibia','name_ar'=>'ناميبيا'],
            ['iso2'=>'NR','iso3'=>'NRU','name_en'=>'Nauru','name_ar'=>'ناورو'],
            ['iso2'=>'NP','iso3'=>'NPL','name_en'=>'Nepal','name_ar'=>'نيبال'],
            ['iso2'=>'NL','iso3'=>'NLD','name_en'=>'Netherlands','name_ar'=>'هولندا'],
            ['iso2'=>'NZ','iso3'=>'NZL','name_en'=>'New Zealand','name_ar'=>'نيوزيلندا'],
            ['iso2'=>'NI','iso3'=>'NIC','name_en'=>'Nicaragua','name_ar'=>'نيكاراغوا'],
            ['iso2'=>'NE','iso3'=>'NER','name_en'=>'Niger','name_ar'=>'النيجر'],
            ['iso2'=>'NG','iso3'=>'NGA','name_en'=>'Nigeria','name_ar'=>'نيجيريا'],
            ['iso2'=>'MK','iso3'=>'MKD','name_en'=>'North Macedonia','name_ar'=>'مقدونيا الشمالية'],
            ['iso2'=>'NO','iso3'=>'NOR','name_en'=>'Norway','name_ar'=>'النرويج'],
            ['iso2'=>'OM','iso3'=>'OMN','name_en'=>'Oman','name_ar'=>'عُمان'],
            ['iso2'=>'PK','iso3'=>'PAK','name_en'=>'Pakistan','name_ar'=>'باكستان'],
            ['iso2'=>'PW','iso3'=>'PLW','name_en'=>'Palau','name_ar'=>'بالاو'],
            ['iso2'=>'PA','iso3'=>'PAN','name_en'=>'Panama','name_ar'=>'بنما'],
            ['iso2'=>'PG','iso3'=>'PNG','name_en'=>'Papua New Guinea','name_ar'=>'بابوا غينيا الجديدة'],
            ['iso2'=>'PY','iso3'=>'PRY','name_en'=>'Paraguay','name_ar'=>'باراغواي'],
            ['iso2'=>'PE','iso3'=>'PER','name_en'=>'Peru','name_ar'=>'بيرو'],
            ['iso2'=>'PH','iso3'=>'PHL','name_en'=>'Philippines','name_ar'=>'الفلبين'],
            ['iso2'=>'PL','iso3'=>'POL','name_en'=>'Poland','name_ar'=>'بولندا'],
            ['iso2'=>'PT','iso3'=>'PRT','name_en'=>'Portugal','name_ar'=>'البرتغال'],
            ['iso2'=>'QA','iso3'=>'QAT','name_en'=>'Qatar','name_ar'=>'قطر'],
            ['iso2'=>'RO','iso3'=>'ROU','name_en'=>'Romania','name_ar'=>'رومانيا'],
            ['iso2'=>'RU','iso3'=>'RUS','name_en'=>'Russia','name_ar'=>'روسيا'],
            ['iso2'=>'RW','iso3'=>'RWA','name_en'=>'Rwanda','name_ar'=>'رواندا'],
            ['iso2'=>'KN','iso3'=>'KNA','name_en'=>'Saint Kitts and Nevis','name_ar'=>'سانت كيتس ونيفيس'],
            ['iso2'=>'LC','iso3'=>'LCA','name_en'=>'Saint Lucia','name_ar'=>'سانت لوسيا'],
            ['iso2'=>'VC','iso3'=>'VCT','name_en'=>'Saint Vincent and the Grenadines','name_ar'=>'سانت فنسنت والغرينادين'],
            ['iso2'=>'WS','iso3'=>'WSM','name_en'=>'Samoa','name_ar'=>'ساموا'],
            ['iso2'=>'SM','iso3'=>'SMR','name_en'=>'San Marino','name_ar'=>'سان مارينو'],
            ['iso2'=>'ST','iso3'=>'STP','name_en'=>'Sao Tome and Principe','name_ar'=>'ساو تومي وبرينسيبي'],
            ['iso2'=>'SA','iso3'=>'SAU','name_en'=>'Saudi Arabia','name_ar'=>'السعودية'],
            ['iso2'=>'SN','iso3'=>'SEN','name_en'=>'Senegal','name_ar'=>'السنغال'],
            ['iso2'=>'RS','iso3'=>'SRB','name_en'=>'Serbia','name_ar'=>'صربيا'],
            ['iso2'=>'SC','iso3'=>'SYC','name_en'=>'Seychelles','name_ar'=>'سيشل'],
            ['iso2'=>'SL','iso3'=>'SLE','name_en'=>'Sierra Leone','name_ar'=>'سيراليون'],
            ['iso2'=>'SG','iso3'=>'SGP','name_en'=>'Singapore','name_ar'=>'سنغافورة'],
            ['iso2'=>'SK','iso3'=>'SVK','name_en'=>'Slovakia','name_ar'=>'سلوفاكيا'],
            ['iso2'=>'SI','iso3'=>'SVN','name_en'=>'Slovenia','name_ar'=>'سلوفينيا'],
            ['iso2'=>'SB','iso3'=>'SLB','name_en'=>'Solomon Islands','name_ar'=>'جزر سليمان'],
            ['iso2'=>'SO','iso3'=>'SOM','name_en'=>'Somalia','name_ar'=>'الصومال'],
            ['iso2'=>'ZA','iso3'=>'ZAF','name_en'=>'South Africa','name_ar'=>'جنوب أفريقيا'],
            ['iso2'=>'SS','iso3'=>'SSD','name_en'=>'South Sudan','name_ar'=>'جنوب السودان'],
            ['iso2'=>'ES','iso3'=>'ESP','name_en'=>'Spain','name_ar'=>'إسبانيا'],
            ['iso2'=>'LK','iso3'=>'LKA','name_en'=>'Sri Lanka','name_ar'=>'سريلانكا'],
            ['iso2'=>'SD','iso3'=>'SDN','name_en'=>'Sudan','name_ar'=>'السودان'],
            ['iso2'=>'SR','iso3'=>'SUR','name_en'=>'Suriname','name_ar'=>'سورينام'],
            ['iso2'=>'SE','iso3'=>'SWE','name_en'=>'Sweden','name_ar'=>'السويد'],
            ['iso2'=>'CH','iso3'=>'CHE','name_en'=>'Switzerland','name_ar'=>'سويسرا'],
            ['iso2'=>'SY','iso3'=>'SYR','name_en'=>'Syria','name_ar'=>'سوريا'],
            ['iso2'=>'TJ','iso3'=>'TJK','name_en'=>'Tajikistan','name_ar'=>'طاجيكستان'],
            ['iso2'=>'TZ','iso3'=>'TZA','name_en'=>'Tanzania','name_ar'=>'تنزانيا'],
            ['iso2'=>'TH','iso3'=>'THA','name_en'=>'Thailand','name_ar'=>'تايلاند'],
            ['iso2'=>'TL','iso3'=>'TLS','name_en'=>'Timor-Leste','name_ar'=>'تيمور الشرقية'],
            ['iso2'=>'TG','iso3'=>'TGO','name_en'=>'Togo','name_ar'=>'توغو'],
            ['iso2'=>'TO','iso3'=>'TON','name_en'=>'Tonga','name_ar'=>'تونغا'],
            ['iso2'=>'TT','iso3'=>'TTO','name_en'=>'Trinidad and Tobago','name_ar'=>'ترينيداد وتوباغو'],
            ['iso2'=>'TN','iso3'=>'TUN','name_en'=>'Tunisia','name_ar'=>'تونس'],
            ['iso2'=>'TR','iso3'=>'TUR','name_en'=>'Turkey','name_ar'=>'تركيا'],
            ['iso2'=>'TM','iso3'=>'TKM','name_en'=>'Turkmenistan','name_ar'=>'تركمانستان'],
            ['iso2'=>'TV','iso3'=>'TUV','name_en'=>'Tuvalu','name_ar'=>'توفالو'],
            ['iso2'=>'UG','iso3'=>'UGA','name_en'=>'Uganda','name_ar'=>'أوغندا'],
            ['iso2'=>'UA','iso3'=>'UKR','name_en'=>'Ukraine','name_ar'=>'أوكرانيا'],
            ['iso2'=>'AE','iso3'=>'ARE','name_en'=>'United Arab Emirates','name_ar'=>'الإمارات'],
            ['iso2'=>'GB','iso3'=>'GBR','name_en'=>'United Kingdom','name_ar'=>'المملكة المتحدة'],
            ['iso2'=>'US','iso3'=>'USA','name_en'=>'United States','name_ar'=>'الولايات المتحدة'],
            ['iso2'=>'UY','iso3'=>'URY','name_en'=>'Uruguay','name_ar'=>'أوروغواي'],
            ['iso2'=>'UZ','iso3'=>'UZB','name_en'=>'Uzbekistan','name_ar'=>'أوزبكستان'],
            ['iso2'=>'VU','iso3'=>'VUT','name_en'=>'Vanuatu','name_ar'=>'فانواتو'],
            ['iso2'=>'VE','iso3'=>'VEN','name_en'=>'Venezuela','name_ar'=>'فنزويلا'],
            ['iso2'=>'VN','iso3'=>'VNM','name_en'=>'Vietnam','name_ar'=>'فيتنام'],
            ['iso2'=>'YE','iso3'=>'YEM','name_en'=>'Yemen','name_ar'=>'اليمن'],
            ['iso2'=>'ZM','iso3'=>'ZMB','name_en'=>'Zambia','name_ar'=>'زامبيا'],
            ['iso2'=>'ZW','iso3'=>'ZWE','name_en'=>'Zimbabwe','name_ar'=>'زيمبابوي'],

            // ✅ إضافات للوصول لـ 196:
            ['iso2'=>'PS','iso3'=>'PSE','name_en'=>'Palestine','name_ar'=>'فلسطين'],
            ['iso2'=>'VA','iso3'=>'VAT','name_en'=>'Vatican City','name_ar'=>'الفاتيكان'],
            ['iso2'=>'TW','iso3'=>'TWN','name_en'=>'Taiwan','name_ar'=>'تايوان'],
        ];
    }
}
